name: Phlex fix style
run-name: ${{ github.actor }} fixing code style

on:
  issue_comment:
    types:
      - created

permissions:
   pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    if: ${{ github.event.issue.pull_request }}

    outputs:
      status: ${{ steps.check_comment.conclusion }}

    steps:
      - id: check_comment
        name: Check comment
        run: |
          comment="${{ github.event.comment.body }}"
          echo $comment | grep -qE '@phlexbot[[:space:]]+style'

  apply_formatting:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'success'
    steps:
      - name: Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Applying code-formatting

      # - uses: actions/checkout@v4
      #   with:
      #     path: phlex-src
      #
      # - uses: DoozyX/clang-format-lint-action@v0.20
      #   with:
      #     source: "./phlex-src"
      #     clangFormatVersion: 20
      #     inplace: True
      #
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: "github-actions[bot]"
      #     author_email: "41898282+github-actions[bot]@users.noreply.github.com"
      #     message: 'Committing clang-format changes'
