name: Phlex fix format
run-name: ${{ github.actor }} fixing code format

on:
  issue_comment:
    types:
      - created

permissions:
   pull-requests: write
   contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check for phlexbot token
    if: ${{ github.event.issue.pull_request }}

    outputs:
      match_result: ${{ steps.check_comment.outputs.match_result }}
      ref_name: ${{ steps.check_comment.outputs.ref_name }}

    steps:
      - id: check_comment
        name: Check comment
        run: |
          comment="${{ github.event.comment.body }}"
          match_result=$(echo $comment | grep -qE '@phlexbot[[:space:]]+format' && echo match || echo non_match)
          echo match_result="$match_result" >> $GITHUB_OUTPUT

          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO="${{ github.repository }}"
          gh api "repos/$REPO/pulls/$ISSUE_NUMBER" > pr.json
          echo "ref_name=$(jq -r .head.ref pr.json)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

  apply_formatting:
    runs-on: ubuntu-latest
    name: Apply formatting
    needs: check
    if: ${{ needs.check.outputs.match_result == 'match' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: phlex-src
          ref: ${{ needs.check.outputs.ref_name }}

      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "./phlex-src"
          clangFormatVersion: 20
          inplace: True

      - uses: EndBug/add-and-commit@v9
        id: add_and_commit
        with:
          cwd: phlex-src
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: 'Committing clang-format changes'

      - name: Formatting changes committed and pushed
        if: ${{ steps.add_and_commit.outputs.committed == 'true' && steps.add_and_commit.outputs.pushed == 'true'}}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Code-formatting changes pushed (commit ${{ steps.add_and_commit.outputs.commit_sha }})

      - name: No formatting changes to make
        if: ${{ steps.add_and_commit.outputs.committed == 'false' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            No code-formatting changes to make
